development:
  adapter: postgresql
  encoding: unicode
  database: ambass_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ambass_production
  pool: 5
  username: postgres
  password:
